**What is Numpy??**<hr/>
NumPy, which stands for "Numerical Python," is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.

NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering


In [2]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3,4,5], [1,2,3,4,5]])
c = np.array([[[1,2,3,4,5], [1,2,3,4,5]], [[1,2,3,4,5], [1,2,3,4,5]]])
d = np.array([[[[1,2,3,4,5], [1,2,3,4,5]], [[1,2,3,4,5], [1,2,3,4,5]]], [[[1,2,3,4,5], [1,2,3,4,5]], [[1,2,3,4,5], [1,2,3,4,5]]]])

print('a:', a)
print()
print('b:', b)
print()
print('c:', c)
print()
print('d:', d)
print()
print('dimension of a:', a.ndim)
print('dimension of b:', b.ndim)
print('dimension of c:', c.ndim)
print('dimension of d:', d.ndim)

print('shape of a:', a.shape)
print('shape of b:', b.shape)
print('shape of c:', c.shape)
print('shape of d:', d.shape)


a: [1 2 3 4 5]

b: [[1 2 3 4 5]
 [1 2 3 4 5]]

c: [[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]

d: [[[[1 2 3 4 5]
   [1 2 3 4 5]]

  [[1 2 3 4 5]
   [1 2 3 4 5]]]


 [[[1 2 3 4 5]
   [1 2 3 4 5]]

  [[1 2 3 4 5]
   [1 2 3 4 5]]]]

dimension of a: 1
dimension of b: 2
dimension of c: 3
dimension of d: 4
shape of a: (5,)
shape of b: (2, 5)
shape of c: (2, 2, 5)
shape of d: (2, 2, 2, 5)


**Create a NumPy ndarray Object**<hr/>
NumPy is used to work with arrays. The array object in NumPy is called ndarray. We can create a NumPy ndarray object by using the array() function.

**Dimensions in Arrays**
##### 1) 0-D Arrays 
    - 0-D arrays, or Scalars, are the elements in an array. 
    - Each value in an array is a 0-D array.
##### 2) 1-D Arrays
    - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
    - These are the most common and basic arrays.
##### 3) 2-D Arrays
    - An array that has 1-D arrays as its elements is called a 2-D array.
    -These are often used to represent matrix or 2nd order tensors.
##### 4) 3-D arrays
    - An array that has 2-D arrays (matrices) as its elements is called 3-D array.
    - These are often used to represent a 3rd order tensor.

In [16]:
import numpy as np

arr = np.array([True, False, True], dtype = np.bool)
print(arr)


[ True False  True]


In [28]:
import numpy as np

arr = np.array(['apple', 2, 3.5], dtype = np.object_)
print(arr)


['apple' 2 3.5]


In [32]:
import numpy as np

arr = np.array(['hello', ' world'], dtype = np.bytes_)
print(arr)


[b'hello' b' world']
