In [8]:
import numpy as np 

arr  = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np
arr = np.arange(1, 15)
print(arr)

print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])
print(arr[arr > 8])
print(arr[arr % 2 == 0])

arr[arr % 2 == 0] = 0

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [6]:
import numpy as np
arr = np.arange(1,8)

print(arr + 2)
print(arr * 2)
print(arr ** 2)

[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [10]:
import numpy as np

arr = np.array([10, 20, 30 ,25, 6, 2])

print("minimum number in array : ", np.min(arr))
print("maximum number in array : ", np.max(arr))
# print("", np.min(arr, axis=0))
# print("", np.max(arr, axis=0))
print("index at which max number is present : ", np.argmax(arr))
print("index at which min number is present : ", np.argmin(arr))
print("square root of element in array : ", np.sqrt(arr))
print("standard deviation of each element in array", np.std(arr))
print("variance of each element in array", np.var(arr))
print("sin of element in array", np.cos(arr))
print("cos of element in array", np.cos(arr))


minimum number in array :  2
maximum number in array :  30
index at which max number is present :  2
index at which min number is present :  5
square root of element in array :  [3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
standard deviation of each element in array 10.19395245558202
variance of each element in array 103.91666666666667
sin of element in array [-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]
cos of element in array [-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [12]:
import numpy as np

np.random.seed(12345)
mat = np.random.randint(1, 21, 9).reshape(3, 3)
print("mat : ", mat)
print("sum", np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print("------------------------------")
print(np.sum(mat, axis=0))
print(np.sum(mat, axis=1))
print(np.min(mat, axis=0))
print(np.min(mat, axis=1))
print(np.max(mat, axis=0))
print(np.max(mat, axis=1))
print(np.cumsum(mat, axis=0))
print(np.cumsum(mat, axis=1))

[[ 3  6  2]
 [ 5 10  6]
 [ 3  2 18]]
55
[ 3  9 11 16 26 32 35 37 55]
2
18
------------------------------
[11 18 26]
[11 21 23]
[3 2 2]
[2 5 2]
[ 5 10 18]
[ 6 10 18]
[[ 3  6  2]
 [ 8 16  8]
 [11 18 26]]
[[ 3  9 11]
 [ 5 15 21]
 [ 3  5 23]]


In [46]:
import numpy as np
def cumsum(arr):
    sum = 0
    
    for i in arr:
        for j in i:
            sum += j
    return sum


arr = np.array([[1,2,3,4,5], [1,2,3,4,5]])
# print(arr)
s = cumsum(arr)
print(s)

[[1 2 3 4 5]
 [1 2 3 4 5]]
30


In [50]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr2 = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(arr1)
print()
print(arr2)
print()
print(np.vstack((arr1, arr2)))
print()
print(np.hstack((arr1, arr2)))  


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [52]:
import numpy as np

np.random.seed(123)
arr1 = np.random.randint(1, 21, 9).reshape(3, 3)
arr2 = np.random.randint(50, 71, 9).reshape(3, 3)

print(arr1)
print()
print(arr2)
print()
print(np.vstack((arr1, arr2)))
print()
print(np.hstack((arr1, arr2)))  


[[14  3  3]
 [ 7 18 20]
 [11  2  1]]

[[67 65 59]
 [50 64 50]
 [65 69 64]]

[[14  3  3]
 [ 7 18 20]
 [11  2  1]
 [67 65 59]
 [50 64 50]
 [65 69 64]]

[[14  3  3 67 65 59]
 [ 7 18 20 50 64 50]
 [11  2  1 65 69 64]]


In [ ]:
import numpy as np

np.random.seed(12345)
mat = np.random.randint(1, 21, 9).reshape(3, 3)
print("mat : \n", mat)

np.random.shuffle(mat)
print("shuffled mat : \n", mat)
# print(np.unique(mat, return_index=True))
print(np.unique(mat, return_index=True, return_counts=True))
print(np.unique(mat).size)

mat : 
 [[ 3  6  2]
 [ 5 10  6]
 [ 3  2 18]]
shuffled mat : 
 [[ 3  6  2]
 [ 5 10  6]
 [ 3  2 18]]
(array([ 2,  3,  5,  6, 10, 18], dtype=int32), array([2, 0, 3, 1, 4, 8]))
(array([ 2,  3,  5,  6, 10, 18], dtype=int32), array([2, 0, 3, 1, 4, 8]), array([2, 2, 1, 2, 1, 1]))
6


In [ ]:
import numpy as np

np.random.seed(12345)
mat = np.random.randint(1, 21, 9).reshape(3, 3)
print("mat : \n", mat)

np.random.shuffle(mat)
print("shuffled mat : \n", mat)
# print(np.unique(mat, return_index=True))
print(np.unique(mat, return_index=True, return_counts=True))
print(np.unique(mat).size)

mat : 
 [[ 3  6  2]
 [ 5 10  6]
 [ 3  2 18]]
shuffled mat : 
 [[ 3  6  2]
 [ 5 10  6]
 [ 3  2 18]]
(array([ 2,  3,  5,  6, 10, 18], dtype=int32), array([2, 0, 3, 1, 4, 8]))
(array([ 2,  3,  5,  6, 10, 18], dtype=int32), array([2, 0, 3, 1, 4, 8]), array([2, 2, 1, 2, 1, 1]))
6
