In [11]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = arr[1:4]
print(arr, sep=', ')
print(arr2, sep=', ')

arr2[1] = 100
print(arr, sep=', ')
print(arr2, sep=', ')

[1 2 3 4 5]
[2 3 4]
[  1   2 100   4   5]
[  2 100   4]


##### **`copy()`**<hr/> The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
 
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


##### **`view()`**<hr/> The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]



##### **`zeros()`**<hr/> The zero function returns a new array of given shape and type, filled with zeros.

In [13]:
import numpy as np
arr = np.zeros((5, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
import numpy as np
arr = np.zeros((4,4)) + 9
print(arr)

[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


##### **`ones()`**<hr/> The ones() function returns a new array of given shape and type, filled with ones.

In [31]:
# create array with hetrogeneous data type
arr = np.ones((3,3), dtype=int ) # dtype=[(x, int)]
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]



##### **`eye()`**<hr/> The eye function is used to create a matrix with 1s on the diagonal and 0s elsewhere.

In [21]:
import numpy
arr4 = numpy.eye(3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



##### **`diag()`**<hr/> The diag function returns the diagonal elements of a matrix.

In [22]:
import numpy
arr4 = numpy.diag((7, 10 ,15))
print(arr4)

[[ 7  0  0]
 [ 0 10  0]
 [ 0  0 15]]


In [34]:
import numpy

arr = numpy.array([[10, 20, 30], [40, 50, 60]])
print(arr)

arr4 = numpy.diag((7, 10 ,15))
print(arr4)

[[10 20 30]
 [40 50 60]]
[[ 7  0  0]
 [ 0 10  0]
 [ 0  0 15]]


In [37]:
import numpy

arr4 = numpy.diag((5, 96 ,3,2, 1))
print(arr4)

[[ 5  0  0  0  0]
 [ 0 96  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  2  0]
 [ 0  0  0  0  1]]


##### **`rand()`**<hr/> The rand function returns a floating-point value between 0 and 1.
##### **`randint()`**<hr/> The randint function returns a random integer between the specified values.

In [45]:
rand = np.random.randint(1, 10,4)
print(rand)

[6 4 2 6]


In [46]:
rand = np.random.rand(2,3)  # rand(rows, column)
print(rand)

[[0.41914167 0.25498473 0.83789355]
 [0.12455401 0.53144529 0.43517319]]


#### **`reshape()`**<hr/>
- The reshape function in NumPy allows you to change the shape (dimensions) of an array without changing its data. 
- This can be useful when you want to rearrange the way data is organized in an array, such as converting a 1-dimensional array into a 2-dimensional matrix or vice versa, or changing the size of a multi-dimensional array while maintaining the total number of elements.
- That means if you start with the same seed and use the same sequence of random number generation operations, you will get the same sequence of random numbers every time.
- This can be useful in situations where you need predictable random numbers for debugging, testing, or simulations.

In [47]:
import numpy as np

random_numbers = np.random.randint(1, 100, 10)
print(random_numbers)

random_numbers = random_numbers.reshape(2, 5)
print(random_numbers)

[36 67 17 81  4 24 42  3 24 26]
[[36 67 17 81  4]
 [24 42  3 24 26]]


In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr = arr.reshape(4,3)
print(arr, '\n')

print("values of Array[0][1] : ", arr[0][1])
print("values of Array[1][0] : ", arr[1][0])
print("shape of array : ", arr.shape, '\n')

arr = arr.reshape(-1,4)
print(f"reshape of array in (-1, 4) : \n{arr} \n")

arr = arr.reshape(2,-1)
print(f"reshape of array in (2, -1) : \n{arr}")


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

values of Array[0][1] :  2
values of Array[1][0] :  4
shape of array :  (4, 3) 

reshape of array in (-1, 4) : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

reshape of array in (2, -1) : 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


##### **`seed()`**<hr/> The seed function is used to initialize the internal state of the random number generator. It takes a single integer argument and uses it to initialize the generator.

In [75]:
import numpy as np

np.random.seed(10)
arr = np.random.randint(0,500,30).reshape(6,5)
print(arr, '\n')
arr
print(arr[2:, 2:], '\n')
print(arr[3:5, 2:4], '\n')

[[265 125 484  15 320]
 [369 123 156 473 221]
 [496 413 369   8  73]
 [256 490  40 420 371]
 [ 16 356 239 395  54]
 [344 363 122  62  33]] 

[[369   8  73]
 [ 40 420 371]
 [239 395  54]
 [122  62  33]] 

[[ 40 420]
 [239 395]] 



In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
slicing = arr[4:9]
print(arr)
print(slicing)

print(type(arr))
print(type(slicing))

slicing[:] = 0
print(arr)
print(slicing)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 1  2  3  4  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19 20]
[0 0 0 0 0]
