#### 1. Convert the below list into numpy array then display the array <hr/>
Input : `my_list[1, 2, 3, 4, 5]`<br/>
Output: `Numpy_array[1 2 3 4 5]`

In [7]:
import numpy as np
my_list = [1,2,3,4,5]
Numpy_array = np.array(my_list)
print(Numpy_array)

[1 2 3 4 5]


#### 2. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.<hr/>

Input : `my_list[1, 2, 3, 4, 5]`<br/>
Output : <br/>
`First Element : 1`<br/>
`Last Element : 5`<br/>
`Array after doubling each element : [2 4 6 8 10]`

In [8]:
import numpy as np
my_list = [1,2,3,4,5]
numpy_array = np.array(my_list)

print("First Element : ", numpy_array[0])
print("Last Element : ", numpy_array[-1])
print("After doublingeach element : ", numpy_array*2)

First Element :  1
Last Element :  5
After doublingeach element :  [ 2  4  6  8 10]


## Lab3 : Working with NUmPy Arrays

#### 1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

Sample Output: <br/>
`An array of 10 zeros:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`<br/>
`An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]`<br/>
`An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]`


In [9]:
import numpy as np

zero_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.zeros(10) + 5

print ("An array of 10 zeros : ", zero_array)
print ("An array of 10 ones : ", ones_array)
print ("An array of 10 fives : ", fives_array)

An array of 10 zeros :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives :  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Sample Output <br/>
[<br/>
    [ 2  3  4] <br/>
    [ 5  6  7] <br/>
    [ 8  9 10] <br/>
]

In [10]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
